"""add soil pressure and joint cache tables

Revision ID: 281011a1bde8
Revises: 341127f8e0a8
Create Date: 2025-11-11 16:28:10.937262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281011a1bde8'
down_revision: Union[str, Sequence[str], None] = '341127f8e0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joint_results_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_set_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('shell_object', sa.String(length=50), nullable=False),
    sa.Column('unique_name', sa.String(length=50), nullable=False),
    sa.Column('results_matrix', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['result_set_id'], ['result_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_joint_cache_lookup', 'joint_results_cache', ['project_id', 'result_set_id', 'result_type'], unique=False)
    op.create_index('ix_joint_cache_unique', 'joint_results_cache', ['project_id', 'result_set_id', 'result_type', 'unique_name'], unique=True)
    op.create_table('soil_pressures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_set_id', sa.Integer(), nullable=True),
    sa.Column('result_category_id', sa.Integer(), nullable=True),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('shell_object', sa.String(length=50), nullable=False),
    sa.Column('unique_name', sa.String(length=50), nullable=False),
    sa.Column('min_pressure', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_categories.id'], ),
    sa.ForeignKeyConstraint(['result_set_id'], ['result_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_soilpressure_loadcase', 'soil_pressures', ['load_case_id'], unique=False)
    op.create_index('ix_soilpressure_project_resultset', 'soil_pressures', ['project_id', 'result_set_id'], unique=False)
    op.create_index('ix_soilpressure_unique', 'soil_pressures', ['project_id', 'result_set_id', 'unique_name', 'load_case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_soilpressure_unique', table_name='soil_pressures')
    op.drop_index('ix_soilpressure_project_resultset', table_name='soil_pressures')
    op.drop_index('ix_soilpressure_loadcase', table_name='soil_pressures')
    op.drop_table('soil_pressures')
    op.drop_index('ix_joint_cache_unique', table_name='joint_results_cache')
    op.drop_index('ix_joint_cache_lookup', table_name='joint_results_cache')
    op.drop_table('joint_results_cache')
    # ### end Alembic commands ###
