"""Add comparison_sets table

Revision ID: 341127f8e0a8
Revises: f0c2a9df3360
Create Date: 2025-11-10 10:20:05.614438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341127f8e0a8'
down_revision: Union[str, Sequence[str], None] = 'f0c2a9df3360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result_set_ids', sa.JSON(), nullable=False),
    sa.Column('result_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_comparisonset', 'comparison_sets', ['project_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_comparisonset', table_name='comparison_sets')
    op.drop_table('comparison_sets')
    # ### end Alembic commands ###
