"""add_time_series_global_cache

Revision ID: 6361e378f827
Revises: ae19a549f0f7
Create Date: 2026-01-09 17:30:25.115684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6361e378f827'
down_revision: Union[str, Sequence[str], None] = 'ae19a549f0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_series_global_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_set_id', sa.Integer(), nullable=False),
    sa.Column('load_case_name', sa.String(length=100), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('time_steps', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('story_sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['result_set_id'], ['result_sets.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ts_global_lookup', 'time_series_global_cache', ['project_id', 'result_set_id', 'load_case_name', 'result_type', 'direction'], unique=False)
    op.create_index('ix_ts_global_story', 'time_series_global_cache', ['story_id'], unique=False)
    op.create_index('ix_ts_global_unique', 'time_series_global_cache', ['project_id', 'result_set_id', 'load_case_name', 'result_type', 'direction', 'story_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ts_global_unique', table_name='time_series_global_cache')
    op.drop_index('ix_ts_global_story', table_name='time_series_global_cache')
    op.drop_index('ix_ts_global_lookup', table_name='time_series_global_cache')
    op.drop_table('time_series_global_cache')
    # ### end Alembic commands ###
