"""Add ColumnAxial model for minimum axial forces

Revision ID: 7065035a1178
Revises: 83c61a2b19c4
Create Date: 2025-10-28 22:30:37.509522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7065035a1178'
down_revision: Union[str, Sequence[str], None] = '83c61a2b19c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_axials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('result_category_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('min_axial', sa.Float(), nullable=False),
    sa.Column('story_sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_categories.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_colaxial_category', 'column_axials', ['result_category_id'], unique=False)
    op.create_index('ix_colaxial_element_story_case', 'column_axials', ['element_id', 'story_id', 'load_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_colaxial_element_story_case', table_name='column_axials')
    op.drop_index('ix_colaxial_category', table_name='column_axials')
    op.drop_table('column_axials')
    # ### end Alembic commands ###
