"""Initial schema

Revision ID: 75909b3aa369
Revises: 
Create Date: 2025-10-21 20:10:13.558426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75909b3aa369'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('load_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_loadcase', 'load_cases', ['project_id', 'name'], unique=True)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_story', 'stories', ['project_id', 'name'], unique=True)
    op.create_table('elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unique_name', sa.String(length=100), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_element', 'elements', ['project_id', 'element_type', 'unique_name'], unique=True)
    op.create_table('story_accelerations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('max_acceleration', sa.Float(), nullable=True),
    sa.Column('min_acceleration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accel_story_case', 'story_accelerations', ['story_id', 'load_case_id', 'direction'], unique=False)
    op.create_table('story_drifts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('drift', sa.Float(), nullable=False),
    sa.Column('max_drift', sa.Float(), nullable=True),
    sa.Column('min_drift', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drift_story_case', 'story_drifts', ['story_id', 'load_case_id', 'direction'], unique=False)
    op.create_table('story_forces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('force', sa.Float(), nullable=False),
    sa.Column('max_force', sa.Float(), nullable=True),
    sa.Column('min_force', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_force_story_case', 'story_forces', ['story_id', 'load_case_id', 'direction'], unique=False)
    op.create_table('time_history_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('time_step', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timehist_case_result', 'time_history_data', ['load_case_id', 'result_type'], unique=False)
    op.create_index('ix_timehist_element', 'time_history_data', ['element_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timehist_element', table_name='time_history_data')
    op.drop_index('ix_timehist_case_result', table_name='time_history_data')
    op.drop_table('time_history_data')
    op.drop_index('ix_force_story_case', table_name='story_forces')
    op.drop_table('story_forces')
    op.drop_index('ix_drift_story_case', table_name='story_drifts')
    op.drop_table('story_drifts')
    op.drop_index('ix_accel_story_case', table_name='story_accelerations')
    op.drop_table('story_accelerations')
    op.drop_index('ix_project_element', table_name='elements')
    op.drop_table('elements')
    op.drop_index('ix_project_story', table_name='stories')
    op.drop_table('stories')
    op.drop_index('ix_project_loadcase', table_name='load_cases')
    op.drop_table('load_cases')
    op.drop_table('projects')
    # ### end Alembic commands ###
