"""Add ColumnShear model for column shear forces

Revision ID: 83c61a2b19c4
Revises: 56b686bb9ea4
Create Date: 2025-10-28 19:19:41.903953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c61a2b19c4'
down_revision: Union[str, Sequence[str], None] = '56b686bb9ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_shears',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('result_category_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('force', sa.Float(), nullable=False),
    sa.Column('max_force', sa.Float(), nullable=True),
    sa.Column('min_force', sa.Float(), nullable=True),
    sa.Column('story_sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_categories.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_colshear_category', 'column_shears', ['result_category_id'], unique=False)
    op.create_index('ix_colshear_element_story_case', 'column_shears', ['element_id', 'story_id', 'load_case_id', 'direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_colshear_element_story_case', table_name='column_shears')
    op.drop_index('ix_colshear_category', table_name='column_shears')
    op.drop_table('column_shears')
    # ### end Alembic commands ###
