"""add_step_type_to_beam_rotations

Revision ID: ae19a549f0f7
Revises: d3f8a92b1c45
Create Date: 2025-12-25 01:43:18.957674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae19a549f0f7'
down_revision: Union[str, Sequence[str], None] = 'd3f8a92b1c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beam_rotations', sa.Column('step_type', sa.String(length=10), nullable=True))
    op.drop_index(op.f('ix_element_cache_project_type'), table_name='element_results_cache')
    op.create_index('ix_elem_cache_project_type', 'element_results_cache', ['project_id', 'result_type'], unique=False)
    op.drop_index(op.f('ix_global_cache_project_type'), table_name='global_results_cache')
    op.create_index('ix_cache_lookup_project_type', 'global_results_cache', ['project_id', 'result_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cache_lookup_project_type', table_name='global_results_cache')
    op.create_index(op.f('ix_global_cache_project_type'), 'global_results_cache', ['project_id', 'result_type'], unique=False)
    op.drop_index('ix_elem_cache_project_type', table_name='element_results_cache')
    op.create_index(op.f('ix_element_cache_project_type'), 'element_results_cache', ['project_id', 'result_type'], unique=False)
    op.drop_column('beam_rotations', 'step_type')
    # ### end Alembic commands ###
