"""Add ResultSet and GlobalResultsCache for wide-format display

Revision ID: c08260852c0f
Revises: 75909b3aa369
Create Date: 2025-10-22 21:12:58.755915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08260852c0f'
down_revision: Union[str, Sequence[str], None] = '75909b3aa369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('result_category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_resultset', 'result_sets', ['project_id', 'name'], unique=True)
    op.create_table('global_results_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_set_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=50), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('results_matrix', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['result_set_id'], ['result_sets.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cache_lookup', 'global_results_cache', ['project_id', 'result_set_id', 'result_type'], unique=False)
    op.create_index('ix_cache_story', 'global_results_cache', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cache_story', table_name='global_results_cache')
    op.drop_index('ix_cache_lookup', table_name='global_results_cache')
    op.drop_table('global_results_cache')
    op.drop_index('ix_project_resultset', table_name='result_sets')
    op.drop_table('result_sets')
    # ### end Alembic commands ###
