"""Add pushover analysis support with PushoverCase and PushoverCurvePoint models

Revision ID: c69a26130dbf
Revises: bd18a0f517d1
Create Date: 2025-11-22 10:12:02.762216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69a26130dbf'
down_revision: Union[str, Sequence[str], None] = 'bd18a0f517d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushover_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('result_set_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('base_story', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['result_set_id'], ['result_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_pushover_case', 'pushover_cases', ['project_id', 'result_set_id', 'name'], unique=True)
    op.create_table('pushover_curve_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pushover_case_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('displacement', sa.Float(), nullable=False),
    sa.Column('base_shear', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pushover_case_id'], ['pushover_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_curve_case_step', 'pushover_curve_points', ['pushover_case_id', 'step_number'], unique=False)
    op.add_column('projects', sa.Column('analysis_type', sa.String(length=50), nullable=True))
    op.add_column('result_sets', sa.Column('analysis_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result_sets', 'analysis_type')
    op.drop_column('projects', 'analysis_type')
    op.drop_index('ix_curve_case_step', table_name='pushover_curve_points')
    op.drop_table('pushover_curve_points')
    op.drop_index('ix_project_pushover_case', table_name='pushover_cases')
    op.drop_table('pushover_cases')
    # ### end Alembic commands ###
