"""Add beam_rotations table for beam R3 plastic rotations

Revision ID: f0c2a9df3360
Revises: f2b37dc1d241
Create Date: 2025-10-29 20:34:05.409073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c2a9df3360'
down_revision: Union[str, Sequence[str], None] = 'f2b37dc1d241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beam_rotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('result_category_id', sa.Integer(), nullable=True),
    sa.Column('hinge', sa.String(length=20), nullable=True),
    sa.Column('generated_hinge', sa.String(length=20), nullable=True),
    sa.Column('rel_dist', sa.Float(), nullable=True),
    sa.Column('r3_plastic', sa.Float(), nullable=False),
    sa.Column('max_r3_plastic', sa.Float(), nullable=True),
    sa.Column('min_r3_plastic', sa.Float(), nullable=True),
    sa.Column('story_sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_categories.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beamrot_category', 'beam_rotations', ['result_category_id'], unique=False)
    op.create_index('ix_beamrot_element_story_case', 'beam_rotations', ['element_id', 'story_id', 'load_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_beamrot_element_story_case', table_name='beam_rotations')
    op.drop_index('ix_beamrot_category', table_name='beam_rotations')
    op.drop_table('beam_rotations')
    # ### end Alembic commands ###
