"""Add ColumnRotation model for column rotation results from Fiber Hinge States

Revision ID: f2b37dc1d241
Revises: 7065035a1178
Create Date: 2025-10-29 15:48:36.245145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b37dc1d241'
down_revision: Union[str, Sequence[str], None] = '7065035a1178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_rotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('load_case_id', sa.Integer(), nullable=False),
    sa.Column('result_category_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('max_rotation', sa.Float(), nullable=True),
    sa.Column('min_rotation', sa.Float(), nullable=True),
    sa.Column('story_sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['load_case_id'], ['load_cases.id'], ),
    sa.ForeignKeyConstraint(['result_category_id'], ['result_categories.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_colrot_category', 'column_rotations', ['result_category_id'], unique=False)
    op.create_index('ix_colrot_element_story_case', 'column_rotations', ['element_id', 'story_id', 'load_case_id', 'direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_colrot_element_story_case', table_name='column_rotations')
    op.drop_index('ix_colrot_category', table_name='column_rotations')
    op.drop_table('column_rotations')
    # ### end Alembic commands ###
